{{- if and .Values.serviceAccount .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.fullname" . }}-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm.fullname" . }}-role
rules:
  {{- toYaml .Values.serviceAccount.rules | nindent 2 }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.fullname" . }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm.fullname" . }}-role
{{- end }}
