INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('010','PIEMONTE');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('020','VALLE D''AOSTA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('030','LOMBARDIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('041','PROVINCIA AUT. BOLZANO');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('042','PROVINCIA AUT. TRENTO');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('050','VENETO');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('060','FRIULI VENEZIA GIULIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('070','LIGURIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('080','EMILIA ROMAGNA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('090','TOSCANA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('100','UMBRIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('110','MARCHE');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('120','LAZIO');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('130','ABRUZZO');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('140','MOLISE');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('150','CAMPANIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('160','PUGLIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('170','BASILICATA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('180','CALABRIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('190','SICILIA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('200','SARDEGNA');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('900','ESTERO');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('777','NON DISPONIBILE');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('888','REGIONE DI STATO EUROPEO NON DISPON.');
INSERT INTO ANA_REGIONI (ID_REGIONE,DESCRIZIONE) VALUES ('999','REGIONE DI STATO ESTERO NON DISPON.');

COMMIT;

INSERT INTO ANA_PROVINCE (ID_PROVINCIA,DESCRIZIONE,ID_REGIONE) VALUES ('FG','FOGGIA','160');
INSERT INTO ANA_PROVINCE (ID_PROVINCIA,DESCRIZIONE,ID_REGIONE) VALUES ('BA','BARI','160');
INSERT INTO ANA_PROVINCE (ID_PROVINCIA,DESCRIZIONE,ID_REGIONE) VALUES ('BR','BRINDISI','160');
INSERT INTO ANA_PROVINCE (ID_PROVINCIA,DESCRIZIONE,ID_REGIONE) VALUES ('TA','TARANTO','160');
INSERT INTO ANA_PROVINCE (ID_PROVINCIA,DESCRIZIONE,ID_REGIONE) VALUES ('LE','LECCE','160');
INSERT INTO ANA_PROVINCE (ID_PROVINCIA,DESCRIZIONE,ID_REGIONE) VALUES ('BT','BARLETTA-ANDRIA-TRANI','160');

COMMIT;

INSERT INTO ANA_COMUNI (ID_COMUNE,FISCALE,PROVINCIA,DESCRIZIONE,ID_REGIONE) VALUES ('000000','','','','777');

COMMIT;