{{- $helm_full_name := include "helm.fullname" . }}
{{- if and .Values.statefulset .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if and .Values.statefulset .Values.statefulset.enabled }}
  serviceName: {{ include "helm.fullname" . }}
{{- end }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- if and .Values.serviceAccount .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "helm.fullname" . }}-sa
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.volConfigMap.enabled }}
      - name: {{ include "helm.fullname" . }}-cm-vol
        configMap:
          name: {{ include "helm.fullname" . }}-vol
      {{- end }}
      {{- if .Values.persistenceVolume.enabled }}
      - name: {{ include "helm.fullname" . }}-pv
        persistentVolumeClaim:
          claimName: {{ include "helm.fullname" . }}-pvc
      {{- end }}
      {{- range $claim := .Values.existingClaimVolumes }}
      - name: {{ $claim.name }}
        persistentVolumeClaim:
          claimName: {{ $claim.claimName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.hostAliases }}
      hostAliases:
      {{- toYaml .Values.hostAliases  | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{- toYaml .Values.command  | nindent 12}}
          {{- end }}
          {{- if .Values.commandArgs }}
          args: {{- toYaml .Values.commandArgs  | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env: {{- toYaml .Values.env  | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "helm.fullname" . }}-env
            - configMapRef:
                name: {{ include "helm.fullname" . }}-env
          {{- if .Values.envFrom }}
          {{- toYaml .Values.envFrom  | nindent 12}}
          {{- end }}
          {{- if .Values.ports }}
          ports:
          {{- toYaml .Values.ports | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe:
          {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end}}
          volumeMounts:
          {{- if .Values.volConfigMap.enabled -}}
          {{- range .Values.volConfigMap.volumeMount }}
          - name: {{ $helm_full_name }}-cm-vol
          {{-  toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.persistenceVolume.enabled }}
          - name: {{ include "helm.fullname" . }}-pv
            mountPath: {{ .Values.persistenceVolume.mountPath }}
          {{- end }}
          {{- range $claim := .Values.existingClaimVolumes }}
          - name: {{ $claim.name }}
            mountPath: {{ $claim.mountPath }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if not ( and .Values.statefulset .Values.statefulset.enabled ) }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
{{- end }}